name: test-payments

on: pull_request

jobs:
    build:
        runs-on: ubuntu-lastest
        steps:
            - uses: actions/checout@v2
            - run: cd payments && npm install && npm run test:ci
