name: test-orders

on:
    pull_request:
        paths:
            - 'orders/**'

jobs:
    build:
        runs-on: ubuntu-lastest
        steps:
            - uses: actions/checout@v2
            - run: cd orders && npm install && npm run test:ci
