name: test-tickets

on: pull_request

jobs:
    build:
        runs-on: ubuntu-lastest
        steps:
            - uses: actions/checout@v2
            - run: cd tickets && npm install && npm run test:ci
